version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: Passw0rd!
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data

# デフォルトログイン情報
# ユーザ: postgres
# データベース: postgres
